name: Build C++ to WebAssembly

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Ambil repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Emscripten
      - name: Install Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh

      # Compile C++ ke WASM
      - name: Compile C++ to WASM
        run: |
          emcc main.cpp -o main.js -s WASM=1 -s EXPORTED_FUNCTIONS='["_tambah"]' -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap"]'

      # Upload artifact
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: |
            main.js
            main.wasm
