name: Build C++ to WASM

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:latest  # pakai container resmi Emscripten

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile C++ to WASM
        run: |
          emcc main.cpp -o main.js -s WASM=1 -s EXPORTED_FUNCTIONS='["_tambah"]' -s EXTRA_EXPORTED_RUNTIME_METHODS='["cwrap"]'

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build
          path: |
            main.js
            main.wasm
